### ISSUE TITLE
Powerline symbols don't show up on urxvt anymore

### ISSUE THREAD

**Issue by fungible** [sunaku/tamzen-font#10]
Using archlinux. A recent update has rendered the Powerline symbols to show up as boxes in urxvt.

**Comment by sunaku** [comment]
Commit dce0c027b1ceaafcce49ec469e10a6478268aea7 might have caused this problem; try reverting it. :crystal_ball:

**Comment by sunaku** [comment]
Good news: I was able to reproduce the bug and used `git bisect` to find the offending commit da7f8e85fc0f97b3addf582d48707f97f6b944c3.

**Comment by sunaku** [comment]
Got it! The encoding on those BDF fonts retained the original Tamsyn encoding since I stopped using bdf-font-patcher to inject Powerline symbols (they're ported straight from my hand-tuned Powerline BDF font instead).  This makes URxvt think that the TamzenForPowerline fonts don't have any Unicode codepoints (namely the Powerline symbols). :neckbeard: 

```diff
-CHARSET_REGISTRY "ISO10646"
+CHARSET_REGISTRY "ISO8859"
```

**Comment by sunaku** [comment]
Fixed now in commit b211df998009b7e7cf64c2bbd87084b12f876bdb. :santa:  Thanks for reporting this issue! :+1:

**Comment by fungible** [comment]
Thanks for the quick fix
