### ISSUE TITLE
MAC OS X dfont files don't render

### ISSUE THREAD

**Issue by opsxcq** [sunaku/tamzen-font#13]
On Mac OS X Sierra, 10.12.4 (16E195), dfont files are blank. Besides the file not being empty, and I was able to install them on my system. I can't view anything that uses this typeface.

Bellow an image to illustrate this issue, that happens when I open any dfont file from this repository. I tested with other dfont files from other repositories, they install and render perfectly.

![Imgur](http://i.imgur.com/KaRFlUP.png)

**Comment by sunaku** [comment]
Thanks for your report. :+1:  The [dfont files are generated]( https://github.com/sunaku/tamzen-font/blob/master/Rakefile#L223-L245 ) by FontForge, so we should report this upstream. :flags:  This is similar to issue #7 about TTF files, which we reported upstream to FontForge at https://github.com/fontforge/fontforge/issues/2738.

Since I don't own/use a Mac, you are welcome to try your hand at this problem:  :sweat_smile:
* Try generating dfont files with FontForge on MacOSX
* Try creating dfont files directly instead of via FontForge

**Comment by g3g3n3** [comment]
will this ever be fixed? When I open the dfont...it's empty and will not install. Also, when opened with fontforge the character glyphs are empty.

**Comment by sunaku** [comment]
Please try the :sparkles: brand new :sparkles:  TTF version of this font (under the `ttf/` subfolder) instead of dfont:

![2020-05-07 19_52_06-](https://user-images.githubusercontent.com/9863/81365731-cb1a8700-909d-11ea-8640-e4de16db357a.png)

See also:
* https://github.com/sunaku/tamzen-font/issues/7#issuecomment-625604797
* https://github.com/sunaku/tamzen-font/issues/26#issuecomment-625984694

**Comment by sunaku** [comment]
Closing. :policeman: Please use the TTF version of this font (available in the `ttf/` subfolder) instead of dfont.
