### ISSUE TITLE
TamzenForPowerline-24?

### ISSUE THREAD

**Issue by madnight** [sunaku/tamzen-font#28]
This would be very helpful for 4k resolution

**Comment by sunaku** [comment]
Try the TTF version of this font (available in the `ttf/` subfolder), which scales to 24pt and beyond: :rocket: 

![2020-05-08 10_57_52-](https://user-images.githubusercontent.com/9863/81441184-285a1b00-9126-11ea-9522-9e8b3bbe8bd8.png)

**Comment by sunaku** [comment]
I'm closing this issue because the real 24 pixel variant would have to be created by hand. :policeman:  The TTF version of this font (discussed in the previous comment) should suffice for 4K/HiDPI users for the time being.  Nevertheless, feel free to submit a PR containing a hand-crafted 24 pixel variant: I will merge. :+1:

**Comment by iamdavidcz** [comment]
@sunaku please reopen this issue. It would be nice to have 24 pixel variant of this font as 20 pixel looks too small on HiDPI screens.
